export const ADD_CRITERIUM = "ADD_CRITERIUM";
export const REMOVE_CRITERIUM = "REMOVE_CRITERIUM";
export const CLEAR_CRITERIUM = "CLEAR_CRITERIUM";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const COLLAPSE = "COLLAPSE";
export const UPDATE_GUIDE_HEIGHT = "UPDATE_GUIDE_HEIGHT";
export const UPDATE_NAV_HEIGHT = "UPDATE_NAV_HEIGHT";
export const UPDATE_STICKY = "UPDATE_STICKY";
